# Generated by Django 4.2.11 on 2024-03-17 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_subscribed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('V', 'Visa'), ('MC', 'Mastercard'), ('AMEX', 'American Express')], max_length=4)),
                ('name', models.CharField(max_length=100)),
                ('annualFee', models.PositiveIntegerField()),
                ('currentBonus', models.PositiveIntegerField()),
                ('link', models.URLField()),
                ('issuedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.issuer')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_subscribed', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.card')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.subscriber')),
            ],
            options={
                'unique_together': {('subscriber', 'card')},
            },
        ),
    ]
